=== Kibana21/atlas-specs/contracts/schemas/canonical/relationship.v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "urn:atlas:schema:canonical:relationship:v1",
  "title": "Relationship identity row",
  "description": "Immutable: type and endpoints never change; one record per (org, rel_type, from, to, discriminator) (ADR-0001, ADR-0017 §4).",
  "type": "object",
  "additionalProperties": false,
  "required": [
    "org_id",
    "id",
    "rel_type",
    "from_id",
    "to_id",
    "discriminator",
    "created_revision"
  ],
  "properties": {
    "org_id": {
      "$ref": "urn:atlas:schema:canonical:common:v1#/$defs/uuid7"
    },
    "id": {
      "$ref": "urn:atlas:schema:canonical:common:v1#/$defs/uuid7"
    },
    "rel_type": {
      "$ref": "urn:atlas:schema:canonical:common:v1#/$defs/rel_type"
    },
    "from_id": {
      "$ref": "urn:atlas:schema:canonical:common:v1#/$defs/uuid7"
    },
    "to_id": {
      "$ref": "urn:atlas:schema:canonical:common:v1#/$defs/uuid7"
    },
    "discriminator": {
      "type": "string",
      "maxLength": 100,
      "description": "Empty unless the relationship type defines one"
    },
    "created_revision": {
      "$ref": "urn:atlas:schema:canonical:common:v1#/$defs/revision"
    }
  }
}

=== Kibana21/atlas-specs/acceptance/test-data/canonical-golden-v1/relationships.json
[
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c18-7c94-b3ed-6912471c3592","id":"01a0c450-6c1d-73f8-8555-7aa9bcf443dd","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c1b-77b4-bba7-bbcf86b946ae"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c1b-77b4-bba7-bbcf86b946ae","id":"01a0c450-6c21-7175-bd7c-a9f533e2dbb9","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c1f-7a0d-8d83-a624c92c7bca"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c1b-77b4-bba7-bbcf86b946ae","id":"01a0c450-6c25-7532-8df6-1f3a5849d115","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c23-7b9c-8216-7cace844d713"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c18-7c94-b3ed-6912471c3592","id":"01a0c450-6c29-7401-bc27-d20076a864ec","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c27-7fb1-ab46-30cbe00cd18a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c27-7fb1-ab46-30cbe00cd18a","id":"01a0c450-6c2d-7344-9430-b4879447b893","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c2b-7745-934d-64baf6d47f81"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c27-7fb1-ab46-30cbe00cd18a","id":"01a0c450-6c31-7b94-a859-1143f23d0f3d","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c2f-7f80-aace-99240be7ca47"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c18-7c94-b3ed-6912471c3592","id":"01a0c450-6c35-76ec-a6cf-7f512db85cb3","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c33-7795-9eee-4c73c1a6d098"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c33-7795-9eee-4c73c1a6d098","id":"01a0c450-6c39-742a-9770-57c385fbf1b7","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c37-7e87-97e3-b114895c1742"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c18-7c94-b3ed-6912471c3592","id":"01a0c450-6c3d-7652-bc80-6e2bd497c19d","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c3b-78d5-867d-b5e3ca802201"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c3f-73d5-9d85-66d3a450d93b","id":"01a0c450-6c43-7009-a88e-fcd98213336c","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"CONTAINS","to_id":"01a0c450-6c41-777c-8c6e-71ba1d000e69"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c65-7480-9265-82d04ebdd28a","id":"01a0c450-6c68-7f0f-9729-353fffb4cae7","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c3f-73d5-9d85-66d3a450d93b"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c6a-7b0d-8425-bde48c2db621","id":"01a0c450-6c6c-7322-a376-bc3133ea49e3","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c45-7acd-9710-c306c76a723a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c6e-7d67-8956-abb92065f3da","id":"01a0c450-6c70-73e0-b091-a8306878ac7b","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c47-7929-9a10-e3e7a8a6b969"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c72-7d8a-93f2-9c7379c3f1c1","id":"01a0c450-6c74-7669-936c-399983c18f90","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c49-7d58-b35a-b7593bbf4ba9"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c76-74f2-98f4-dead3cee18d9","id":"01a0c450-6c78-7b6a-8350-ecfd76f58bef","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c4b-7775-b4e4-87385ed7b9ab"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c7a-751c-a37c-898f87be41a6","id":"01a0c450-6c7e-74fc-b0b6-b11c7ef3ebb1","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c65-7480-9265-82d04ebdd28a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c7a-751c-a37c-898f87be41a6","id":"01a0c450-6c80-7432-ac4d-068523891e2c","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c72-7d8a-93f2-9c7379c3f1c1"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c7a-751c-a37c-898f87be41a6","id":"01a0c450-6c82-7297-b6ae-dbd2a3a7f06f","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c3f-73d5-9d85-66d3a450d93b"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c4d-7191-8527-785f7a889719","id":"01a0c450-6c84-7317-9e7f-0c19782e444f","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"OWNS","to_id":"01a0c450-6c7a-751c-a37c-898f87be41a6"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c86-77f4-a7e6-3d1c28bd7fe8","id":"01a0c450-6c89-7997-8745-bd656939797f","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c65-7480-9265-82d04ebdd28a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c86-77f4-a7e6-3d1c28bd7fe8","id":"01a0c450-6c8b-776d-89d6-010d85588ba8","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c3f-73d5-9d85-66d3a450d93b"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c4d-7191-8527-785f7a889719","id":"01a0c450-6c8d-7b8d-96d8-30f5ad2d6d90","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"OWNS","to_id":"01a0c450-6c86-77f4-a7e6-3d1c28bd7fe8"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c8f-7409-9197-df121206891c","id":"01a0c450-6c92-7d84-9f14-84cd2f82087b","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c65-7480-9265-82d04ebdd28a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c8f-7409-9197-df121206891c","id":"01a0c450-6c94-7b17-9aa7-64b3619e5aeb","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c76-74f2-98f4-dead3cee18d9"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c8f-7409-9197-df121206891c","id":"01a0c450-6c96-7e41-b602-2306577b605f","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c41-777c-8c6e-71ba1d000e69"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c98-7fb2-bb43-f25810052418","id":"01a0c450-6c9c-7800-ba75-8d8166bf5c53","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c6a-7b0d-8425-bde48c2db621"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c98-7fb2-bb43-f25810052418","id":"01a0c450-6c9e-767e-ab86-006e5a863328","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c45-7acd-9710-c306c76a723a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c50-795a-97a6-36614728234b","id":"01a0c450-6ca0-7336-8680-e9c8bf2adf3e","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"OWNS","to_id":"01a0c450-6c98-7fb2-bb43-f25810052418"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6ca2-7bfb-a903-4121455acce0","id":"01a0c450-6ca5-7a4c-81de-4ceec4c56b24","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c6a-7b0d-8425-bde48c2db621"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6ca2-7bfb-a903-4121455acce0","id":"01a0c450-6ca7-76c1-812d-d9a2cf407e4c","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c45-7acd-9710-c306c76a723a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c50-795a-97a6-36614728234b","id":"01a0c450-6ca9-7fd0-abc7-4e411f50dcbb","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"OWNS","to_id":"01a0c450-6ca2-7bfb-a903-4121455acce0"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6cab-72bc-9abb-95f255957e07","id":"01a0c450-6cae-7e6c-8ee6-d3dbdb8774c8","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c6a-7b0d-8425-bde48c2db621"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6cab-72bc-9abb-95f255957e07","id":"01a0c450-6cb0-70a4-b6af-49264ec4d8cc","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c45-7acd-9710-c306c76a723a"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c50-795a-97a6-36614728234b","id":"01a0c450-6cb2-7401-b62a-0b2ae199aafe","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"OWNS","to_id":"01a0c450-6cab-72bc-9abb-95f255957e07"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6cb4-7a73-b483-14d9b4cca835","id":"01a0c450-6cb7-751c-a75b-66a27b722bbb","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c6e-7d67-8956-abb92065f3da"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6cb4-7a73-b483-14d9b4cca835","id":"01a0c450-6cb9-7ce9-88d8-093d25ef1d5f","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c47-7929-9a10-e3e7a8a6b969"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6c53-7c9d-9616-3fe69f4a6358","id":"01a0c450-6cbb-76b4-a5cf-50a41a3ffc9f","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"OWNS","to_id":"01a0c450-6cb4-7a73-b483-14d9b4cca835"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6cbd-71c4-b587-03cf5258a8c4","id":"01a0c450-6cc0-70af-bc4a-805edc2d0396","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c6e-7d67-8956-abb92065f3da"},
{"created_revision":1,"discriminator":"","from_id":"01a0c450-6cbd-71c4-b587-03cf5258a8c4","id":"01a0c450-6cc2-7fe5-a6a5-164a5919b403","org_id":"01a0c450-6c01-76c4-8c39-8171fd4953d6","rel_type":"MEMBER_OF","to_id":"01a0c450-6c47-7929-9a10-e3e7a8a6b969"},
